version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: review_db_downscaled
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: review_api_downscaled
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      # Code and data directories
      - ./backend:/app
      - ./scripts:/app/scripts
      - ./agents:/app/agents
      - ./data:/app/data
      - ./models:/app/models
    env_file:
      - .env
    # GPU support for model inference
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] # Currently a RTX 5070Ti

volumes:
  postgres_data: