openai_api_key: ${OPENAI_API_KEY}

# AWS/MinIO configuration for storing scraped data
aws:
  region_name: "us-east-1"
  # These will be loaded from environment variables
  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  # This endpoint points to your local MinIO service
  endpoint_url: "http://minio:9000"

# Keywords to guide the scraping agent
product_keywords:
  - "ergonomic chair"
  - "office furniture"
  - "mechanical keyboard"